### ISSUE TITLE
change export name

### ISSUE THREAD

**Issue by mariaanasb** [firebase/snippets-node#160]
Hello, is there a way I can define the export file name?

**Comment by samtstern** [comment]
@mariaanasb I am not sure what you're asking, can you clarify your question?  What Firebase product are you trying to use and what issue are you running into?

**Comment by mariaanasb** [comment]
@samtstern hello! 
thank you for your answer. 
I am sorry I was not clear.

I was trying to do the **snippets-node/functions/firestore-export/** and I did it based on this [video](https://www.youtube.com/watch?v=HYOR42pYYzo) but I would like to save the backups with a scpecific name like "backup".
Is this possible?

**Comment by samtstern** [comment]
@mariaanasb no you can't change the name of the actual export files, as you can see the underlying API does not have that option:
https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases/exportDocuments

You can add more to the `outputUriPrefix` to help with organization.  So instead of just `gs://bucketname` I believe you can do `gs://bucketname/somefolder` and the export will be created in there.  But the export will still have the same name.
