### ISSUE TITLE
Importing Documents From Data Exports

### ISSUE THREAD

**Issue by adam-hurwitz** [firebase/snippets-node#32]
**Is there a way to import specific Firestore Database Documents under an exported Collection from Firebase Storage?**

# Observed

After creating a JavaScript AppEngine Cron Job according to the [Schedule Export](https://firebase.google.com/docs/firestore/solutions/schedule-export) documentation there does not seem to be a way to import specific Documents, only Collections.

# Expected

_In-Short_: The ability to export a specified Document representing a user. 

The Firestore database of the app is currently structured with a _users_ Collection at the highest level, and then a Document representing the user containing meta data, saved content, etc. A daily Cron Job has been scheduled with the documentation above in order to back up all of the Firestore data including the user data in the event users' data is inadvertently corrupted during development or maliciously in an attack. 

However, from the [Import specific collections](https://firebase.google.com/docs/firestore/manage-data/export-import#import_specific_collections) documentation it appears only a Collection can be imported. 

**Existing Data Structure**

![screen shot 2019-01-25 at 5 25 25 pm](https://user-images.githubusercontent.com/3938076/51780809-a11a9c80-20c6-11e9-8029-59a69d85e385.png)

- users _collection_ 
   - user_one _document_
         - actions _collection_
             ...
         - categories _collection_
             ...
         - user data fields
   - user_two _document_
          ...

# Potential Solution if Importing Document Impossible

Refactoring the Firestore Database structure to add additional layers of Collections/Documents in order for each User to be represented by a unique Collection. The downside with the new data structure is you have a unnecessary additional `users` _document_ 2nd level.

**New Data Structure**

- users _collection_ 
   - users _document_
      - user_one _collection_
         - actions _document_
             ...
         - categories _document_
             ...
         - user data _document_ w/ fields
              ...
      - user_two collection
      ...

**Comment by samtstern** [comment]
@AdamSHurwitz thanks for the feedback!  Right now there is no way to import anything smaller than a collection when using the managed import/export operations.

Can you help understand your use case for these granular imports?  Are you just doing testing and want to control your inputs?  We have considered a simplified version of the import/export feature for small testing data sets.

**Comment by AdamSHurwitz** [comment]
@samtstern The use case is for production as a precaution in case a user's data is corrupted by a bug, by accident in development, or via an outside attack. 

If for example a user has lost information in their account stored on Firestore Database I could simply import the last snapshot of their user account from Firebase Cloud Storage using the import feature.

**Comment by samtstern** [comment]
@AdamSHurwitz got it, that makes total sense!  I will file the feature request about this, and we'll put it on the list of improvements for import/export (we have a long list there...)

**Comment by AdamSHurwitz** [comment]
# Follow-up

The proposed solution above of exporting all of the Firestore Database and importing a specific user collection does not work. After re-examination of the documentation [Export and Import Data](https://firebase.google.com/docs/firestore/manage-data/export-import) it appears this is the reason.

> You cannot import specific collections from an export of all documents.

The error received when attempting to import a specific user collection from the backup of the entire Firestore Database on Firebase Cloud Storage: 

> ERROR: (gcloud.beta.firestore.import) INVALID_ARGUMENT: The requested kinds/namespaces are not available

# More Advanced Solution

Rather than exporting everything with the broad [Schedule Export](https://firebase.google.com/docs/firestore/solutions/schedule-export) Cron Job method I will follow the [How to Schedule (Cron) Jobs with Cloud Functions for Firebase](https://firebase.googleblog.com/2017/03/how-to-schedule-cron-jobs-with-cloud.html) to run a Cloud Function that exports specific collections to Storage.

This should ensure that a specific user collection can be later retrieved via an import.

**Comment by samtstern** [comment]
> You cannot import specific collections from an export of all documents.

This is actually news to me and seems like something we should improve.  I'll ask around

**Comment by AdamSHurwitz** [comment]
# Update

As I'm preparing for the first public release of my app I re-ran this experiment with the steps outlined above and at a closer examination found that User 1's Document data was reset to the imported snapshot. However, User 1 retained the Collections saved after the time of the snapshot. 

To summarize, when importing an entire Firestore Database from Firebase Cloud Storage the Document data will be overwritten whereas new Collection data from after the time of the snapshot will persist.

**Comment by samtstern** [comment]
@AdamSHurwitz just to clarify you're saying that if you have data like this

User doc:
`/users/123`

User subdoc:
`/users/123/things/456`

That importing `users` collection does not affect the user's `things`.  That makes sense to me as the linking between collections and subcollections is not a "hard" link and all reads and writes are collection-scoped. 

Is this the behavior you wanted / expected or were you hoping for something else?

**Comment by AdamSHurwitz** [comment]
@samtstern 

Originally I had each user in a document `/users/123` and `/users/456` but refactored the user to be it's own collection `/usersCollection/allUsersDoc/user123` and `/usersCollection/allUsersDoc/user456`so that way a user's data can be imported from a Firebase Cloud Storage snapshot.  According to the documentation it indicates only specific Collections can be imported from a snapshot, not Documents.

Then, after realizing specific Collections can only be imported from snapshots of specific Collections, not of the entire Database I decided to test importing the entire database in order to attempt to restore the data for `user123` in the event their data is corrupted.

When the entire Database snapshot is imported with the intent to restore just `user123` it appears both the _Document_ and _Collection_ import as intended. 

However, it is the data for `user456` which does not need to be restored, but is unintentionally affected by the Database wide import that is not desired. For `user456` _Collection_ the contained _Document_ data is overwritten to the time of the import (not-desired as I only want to import data for `user123`), however the sub _Collections_ of `user456` remain intact (expected).

**Comment by samtstern** [comment]
@AdamSHurwitz some more questions:

> 2\. There is currently not a simple approach of exporting specific _Collections_ programmatically.

Isn't that what this flag does?
https://firebase.google.com/docs/firestore/manage-data/export-import#export_specific_collections

> 3\. As a workaround for **#2** the entire database can be exported programmatically on a Cron Job schedule, and imported if needed to restore a user's data with the consequence of other user's _Document_ data being reverted to the import as well.

Why would you not expect importing the whole DB to overwrite all documents?

**Comment by AdamSHurwitz** [comment]
@samtstern 

2. That flag meets the desired functionality. However, it is executed in a manual terminal command.  I need to do implement that command programmatically (ie: within a _Js_ Cron Job or _Java/Kotlin_ Task) so that backups can be done on a schedule for each user.

3.  You are correct. I misread the line below interpreting it as only new document ids would be imported and existing ids would persist, but as it states, existing ids will be overwritten.
> Imports do not assign new document IDs. Imports use the IDs captured at the time of the export. As a document is being imported, its ID is reserved to prevent ID collisions. If a document with the same ID already exists, the import overwrites the existing document.

**Comment by samtstern** [comment]
@AdamSHurwitz for #2 this guide shows how to do things more problematically:
https://firebase.google.com/docs/firestore/solutions/schedule-export

You can see that the export can be triggered using the REST API, no CLI needed.  Since it's a long-running operation you can just fire and forget.  It takes collection IDs as a parameter, although I have no idea how many collections you could specify in a single request.

**Comment by AdamSHurwitz** [comment]
@samtstern, great idea! I will make the REST API request from a [Cloud Function w/ a Cron Job](https://firebase.googleblog.com/2017/03/how-to-schedule-cron-jobs-with-cloud.html). I'm happy to make a public friendly sample as well on Medium to explain to others.

**A few implementation details**

1. If the request is made within the Firebase Cloud Function environment would the headers containing the `accessToken` still be required or is it already authenticated?
    
    `const auth = await google.auth.getClient({`
     `   scopes: ['https://www.googleapis.com/auth/datastore']`
    `});`
    
    `const accessTokenResponse = await auth.getAccessToken();`
    `const accessToken = accessTokenResponse.token;`

2. The `url` will only need to pass the Firebase _projectId_.
`https://firestore.googleapis.com/v1beta1/projects/[myProjectId]/databases/(default):exportDocuments`

3. The required `body` request takes 2 parameters `outputUriPrefix` and `collectionIds` which would look something like this.
**outputUriPrefix**: `/cloud-firestore-export?outputUriPrefix=gs://[myBucketName]/2019-02-08-13-14-85`

**collectionIds**: `user123,user456`

From there the `POST` request may be placed via _Axios_.

**Comment by samtstern** [comment]
> 1. If the request is made within the Firebase Cloud Function environment would the headers containing the `accessToken` still be required or is it already authenticated?

You'll have to add the token yourself, but it should be very easy to get within the CF3 environment because you're already running as a service account.

> 2 and 3

You want to POST to this url:
```
https://firestore.googleapis.com/v1beta1/projects/YOUR_PROJECT_ID/databases/(default):exportDocuments
```

And the body of the POST should be a JSON object with those two parameters:
```
{
  collectionIds: ...
  outputUriPrefix: ...
}
```

Honestly you can copy-paste 90% of the code from here:
https://github.com/firebase/snippets-node/blob/master/firestore/solution-scheduled-backups/app.js

**Comment by AdamSHurwitz** [comment]
Perfect! I've created a ticket for myself for post app release in order to implement.

**Comment by samtstern** [comment]
Also I've filed a FR internally to allow more granular imports from a
full-db export.

**Comment by jonrandahl** [comment]
@samtstern & @AdamSHurwitz thank you for your discussion above and apologies for hijacking this thread!

I have a 24-hour backup running thanks to the [Scheduled Export](https://firebase.google.com/docs/firestore/solutions/schedule-export) documentation; however, I wondered if you could shed a little more light on how you ended up handling the granular export/imports of the individual users below the `all_users` collection?

I have two questions, one for each of you:

1. @samtstern, in your last comment you state:
> Also I've filed a FR internally to allow more granular imports from a
full-db export.

I was wondering if you meant that it is possible to import granular exports into a restored full-db export?

For example, with the final data structure above:
- all_users collection
	- all_users document
		- user_one collection
			- actions document
				...
			- categories document
				...
			- user data document w/ fields
				...
		- user_two collection
			...
		- user_three collection
			...

If I triggered a single user export of the `user_two` collection, could I then import that into a restored full-db backup and **only** replace the `user_two` data?

2. @AdamSHurwitz, you mentioned that you would be ... 
> happy to make a public friendly sample as well on Medium to explain to others 

and I wondered if you had a repo available for that as I couldn't find anything in your article list, but I completely understand if you don't!

Once again, my thanks for your discussion above, it's helped me immensely!

**Comment by samtstern** [comment]
@jonrandahl my understanding is that imports don't replace all of the information in the destination, they just restore all of the documents present in the import.

**Comment by jonrandahl** [comment]
@samtstern thanks for the clarification on my question, I was able to do just that in my own testing today - I also realised I read your comment wrong and now take it to mean that we could, at some point, be able to extract `user_two`'s data from the full-db backup, not a granular export - apologies for the confusion - your FR would be amazing!

**Comment by AdamSHurwitz** [comment]
@jonrandahl I decided against a custom solution and used the approach under the [Schedule data exports](https://firebase.google.com/docs/firestore/solutions/schedule-export) documentation.
